fix(map.jinja): fix useflags regex (gentoo)
* fix(map.jinja): fix useflags regex

When using version inside useflag, the sls_block macro with ebuildpkg regex result in a range error.
Replacing the version argument with uses seem to work as escapes don't really work there.

fix(map.jinja): replace all problematic lines
fix(map.jinja): update available targets

```
----------
          ID: php_install_imagick_dev-php-pecl-imagick
    Function: pkg.installed
        Name: dev-php/pecl-imagick
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib64/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib64/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib64/python3.6/site-packages/salt/states/pkg.py", line 1563, in installed
                  **kwargs)
                File "/usr/lib64/python3.6/site-packages/salt/states/pkg.py", line 651, in _find_install_targets
                  for name, version in desired.items()
                File "/usr/lib64/python3.6/site-packages/salt/states/pkg.py", line 652, in <listcomp>
                  if not (name in cur_pkgs and (version is None or _fulfills_version_string(cur_pkgs[name], version)))
                File "/usr/lib64/python3.6/site-packages/salt/states/pkg.py", line 216, in _fulfills_version_string
                  fullfills_all = fullfills_all and _fulfills_version_spec([installed_version], operator, version_string, ignore_epoch=ignore_epoch)
                File "/usr/lib64/python3.6/site-packages/salt/states/pkg.py", line 234, in _fulfills_version_spec
                  if (oper == '==' and fnmatch.fnmatch(ver, desired_version)) \
                File "/usr/lib64/python3.6/fnmatch.py", line 36, in fnmatch
                  return fnmatchcase(name, pat)
                File "/usr/lib64/python3.6/fnmatch.py", line 70, in fnmatchcase
                  match = _compile_pattern(pat)
                File "/usr/lib64/python3.6/fnmatch.py", line 46, in _compile_pattern
                  return re.compile(res).match
                File "/usr/lib64/python3.6/re.py", line 233, in compile
                  return _compile(pattern, flags)
                File "/usr/lib64/python3.6/re.py", line 301, in _compile
                  p = sre_compile.compile(pattern, flags)
                File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
                  p = sre_parse.parse(p, flags)
                File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
                  p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
                File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
                  not nested and not items))
                File "/usr/lib64/python3.6/sre_parse.py", line 765, in _parse
                  p = _parse_sub(source, state, sub_verbose, nested + 1)
                File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
                  not nested and not items))
                File "/usr/lib64/python3.6/sre_parse.py", line 553, in _parse
                  raise source.error(msg, len(this) + 1 + len(that))
              sre_constants.error: bad character range 7-3 at position 20
     Started: 14:28:26.927898
    Duration: 6321.149 ms
     Changes:
```

* Use single-quoting

Signed-off-by: Mark Gomersbach <markgomersbach@gmail.com>